# Type NodePort to allow free communication between the three main services

apiVersion: v1
kind: Service
metadata:
  name: promptcrm-service
  namespace: promptcrm
spec:
  selector:
    app: promptcrm-db
  ports:
    - port: 1433
      targetPort: 1433
  type: NodePort
