# NAMESPACE: promptsales-db
# This file contains the Persistent Volume Claim for promptsales

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-promptsales-pvc
  namespace: promptsales-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: managed-premium  	# Premium ssd storage from aks