# It will run on the default port for sql service, which is 1433

apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptcontent-deployment
  namespace: promptcontent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: promptcontent-db
  template:
    metadata:
      labels:
        app: promptcontent
    spec:
      containers:
      - name:
        image:
        ports:
          - containerPort: 1433
        
