# NAMESPACE: promptcontent-db
# This pod contains the deployment for the database promptads.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-promptcontent-deployment
  namespace: promptcontent-db
spec:
  replicas: 1 			# Relational databases dont scale
  selector:
    matchLabels:
      app: promptcontent-db
  template:
    metadata:
      labels:
        app: promptcontent-db
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest 	# Official sql server image
        ports:
          - containerPort: 1433
        env:
          - name: ACCEPT_EULA		# Accepts licenses
            value: "Y"
          - name: MSSQL_ENABLE_HADR	# Enables HADR, High Availability Disaster Recovery (failover and replication)
            value: "1"
          - name: MSSQL_SA_PASSWORD	# Adds password information to the environment
            valueFrom:
              secretKeyRef:
                name: sqlserver-promptcontent-secret
                key: MSSQL_SA_PASSWORD
          - name: MSSQL_PID
            value: "Developer"  
        volumeMounts:
          - name: sqlserver-storage
            mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "2Gi"		# The minimum amount of cpu and memory for promptads-db containers.
            cpu: "500m"
          limits:
            memory: "4Gi"		# The maximum amount of cpu and memory for promptads-db containers.
            cpu: "2000m"
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: sqlserver-promptcontent-pvc		# Uses the established values from the pvc.yaml file